jobs:
  check:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./verify/ci

name: Workflow

on:
  schedule:
    - cron: "50 */6 * * *"
